spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5433/payments #create an orders database
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  kafka:
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: notification.PaymentNotificationRequest #mention the object that we are sending

server:
  port: 8060